#ifndef QXTSHORTCUT_GLOBAL_H
#define QXTSHORTCUT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QXTSHORTCUT_LIBRARY)
#  define QXTSHORTCUTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QXTSHORTCUTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QXTSHORTCUT_GLOBAL_H
