#ifndef THREADHANDLE_GLOBAL_H
#define THREADHANDLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(THREADHANDLE_LIBRARY)
#  define THREADHANDLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define THREADHANDLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // THREADHANDLE_GLOBAL_H
